language: node_js
sudo: true
node_js:
  - "8"
install:
  - npm install -g codecov
  - npm install -g cross-env
  - npm install -g nyc
  - npm install
script:
  - npm run test
  - npm run lint
  - npm run coverage
  - cat ./coverage/lcov.info | codecov

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npm run semantic-release
